/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for CSFA_AccessoryType.
 */
@interface CSFA_AccessoryType : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(CSFA_AccessoryType *)value;
@property (class, readonly) CSFA_AccessoryType *HEAD_WEAR;
@property (class, readonly) CSFA_AccessoryType *GLASSES;
@property (class, readonly) CSFA_AccessoryType *MASK;
@end
