/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CSFA_ImageUrl model.
 */
@interface CSFA_ImageUrl : NSObject <AZCodable>
/**
 * Publicly reachable URL of an image.
 */
@property NSString *url;
/**
* Creates an instance of CSFA_ImageUrl class.
* @param url publicly reachable URL of an image.
*/
- (id) initWithUrl:(NSString *)url;
@end
