/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_Gender.h"
#import "CSFA_FacialHair.h"
#import "CSFA_GlassesType.h"
#import "CSFA_HeadPose.h"
#import "CSFA_Emotion.h"
#import "CSFA_Hair.h"
#import "CSFA_Makeup.h"
#import "CSFA_Occlusion.h"
#import "CSFA_Accessory.h"
#import "CSFA_Blur.h"
#import "CSFA_Exposure.h"
#import "CSFA_Noise.h"

/**
 * Face Attributes.
 */
@interface CSFA_FaceAttributes : NSObject <AZCodable>
/**
 * Age in years.
 */
@property AZDouble *age;
/**
 * Possible gender of the face. Possible values include: 'male', 'female',
 * 'genderless'.
 */
@property CSFA_Gender *gender;
/**
 * Smile intensity, a number between [0,1].
 */
@property AZDouble *smile;
/**
 * Properties describing facial hair attributes.
 */
@property CSFA_FacialHair *facialHair;
/**
 * Glasses type if any of the face. Possible values include: 'noGlasses',
 * 'readingGlasses', 'sunglasses', 'swimmingGoggles'.
 */
@property CSFA_GlassesType *glasses;
/**
 * Properties indicating head pose of the face.
 */
@property CSFA_HeadPose *headPose;
/**
 * Properties describing facial emotion in form of confidence ranging from 0 to
 * 1.
 */
@property CSFA_Emotion *emotion;
/**
 * Properties describing hair attributes.
 */
@property CSFA_Hair *hair;
/**
 * Properties describing present makeups on a given face.
 */
@property CSFA_Makeup *makeup;
/**
 * Properties describing occlusions on a given face.
 */
@property CSFA_Occlusion *occlusion;
/**
 * Properties describing any accessories on a given face.
 */
@property NSArray<CSFA_Accessory*> *accessories;
/**
 * Properties describing any presence of blur within the image.
 */
@property CSFA_Blur *blur;
/**
 * Properties describing exposure level of the image.
 */
@property CSFA_Exposure *exposure;
/**
 * Properties describing noise level of the image.
 */
@property CSFA_Noise *noise;
@end
