/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_LargePersonGroup.h"

@implementation CSFA_LargePersonGroup
- (id) initWithLargePersonGroupId:(NSString *)largePersonGroupId {
    self = [super init];
    if (self) {
        _largePersonGroupId = largePersonGroupId;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject:self.largePersonGroupId forKey:@"largePersonGroupId"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super initWithDecoder:decoder]) {
        _largePersonGroupId = [decoder decodeObjectForKey:@"largePersonGroupId" objectClass:[NSString class]];
    }
    return self;
}
@end
