/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_Error.h"

/**
 * Error information returned by the API.
 */
@interface CSFA_APIError : NSObject <AZCodable>
/**
 * The error property.
 */
@property CSFA_Error *error;
@end
