/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_NameAndUserDataContract.h"

@implementation CSFA_NameAndUserDataContract
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.name forKey:@"name"];
    [encoder encodeObject:self.userData forKey:@"userData"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _name = [decoder decodeObjectForKey:@"name" objectClass:[NSString class]];
        _userData = [decoder decodeObjectForKey:@"userData" objectClass:[NSString class]];
    }
    return self;
}
@end
