/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_HairColor.h"

/**
 * Properties describing hair attributes.
 */
@interface CSFA_Hair : NSObject <AZCodable>
/**
 * A number describing confidence level of whether the person is bald.
 */
@property AZDouble *bald;
/**
 * A boolean value describing whether the hair is visible in the image.
 */
@property AZBoolean *invisible;
/**
 * An array of candidate colors and confidence level in the presence of each.
 */
@property NSArray<CSFA_HairColor*> *hairColor;
@end
