/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Properties describing facial hair attributes.
 */
@interface CSFA_FacialHair : NSObject <AZCodable>
/**
 * The moustache property.
 */
@property AZDouble *moustache;
/**
 * The beard property.
 */
@property AZDouble *beard;
/**
 * The sideburns property.
 */
@property AZDouble *sideburns;
@end
