/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_Exposure.h"

@implementation CSFA_Exposure
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.exposureLevel forKey:@"exposureLevel"];
    [encoder encodeObject:self.value forKey:@"value"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _exposureLevel = [decoder decodeObjectForKey:@"exposureLevel" objectClass:[CSFA_ExposureLevel class]];
        _value = [decoder decodeObjectForKey:@"value" objectClass:[AZDouble class]];
    }
    return self;
}
@end
