/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for CSFA_FindSimilarMatchMode.
 */
@interface CSFA_FindSimilarMatchMode : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(CSFA_FindSimilarMatchMode *)value;
@property (class, readonly) CSFA_FindSimilarMatchMode *MATCH_PERSON;
@property (class, readonly) CSFA_FindSimilarMatchMode *MATCH_FACE;
@end
