/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_Noise.h"

@implementation CSFA_Noise
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.noiseLevel forKey:@"noiseLevel"];
    [encoder encodeObject:self.value forKey:@"value"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _noiseLevel = [decoder decodeObjectForKey:@"noiseLevel" objectClass:[CSFA_NoiseLevel class]];
        _value = [decoder decodeObjectForKey:@"value" objectClass:[AZDouble class]];
    }
    return self;
}
@end
