/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * A rectangle within which a face can be found.
 */
@interface CSFA_FaceRectangle : NSObject <AZCodable>
/**
 * The width of the rectangle, in pixels.
 */
@property AZInteger *width;
/**
 * The height of the rectangle, in pixels.
 */
@property AZInteger *height;
/**
 * The distance from the left edge if the image to the left edge of the
 * rectangle, in pixels.
 */
@property AZInteger *left;
/**
 * The distance from the top edge if the image to the top edge of the
 * rectangle, in pixels.
 */
@property AZInteger *top;
/**
* Creates an instance of CSFA_FaceRectangle class.
* @param width the width of the rectangle, in pixels.
* @param height the height of the rectangle, in pixels.
* @param left the distance from the left edge if the image to the left edge of the rectangle, in pixels.
* @param top the distance from the top edge if the image to the top edge of the rectangle, in pixels.
*/
- (id) initWithWidth:(AZInteger *)width withHeight:(AZInteger *)height withLeft:(AZInteger *)left withTop:(AZInteger *)top;
@end
