/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Request to update face data.
 */
@interface CSFA_UpdateFaceRequest : NSObject <AZCodable>
/**
 * User-provided data attached to the face. The size limit is 1KB.
 */
@property NSString *userData;
@end
