/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Properties describing occlusions on a given face.
 */
@interface CSFA_Occlusion : NSObject <AZCodable>
/**
 * A boolean value indicating whether forehead is occluded.
 */
@property AZBoolean *foreheadOccluded;
/**
 * A boolean value indicating whether eyes are occluded.
 */
@property AZBoolean *eyeOccluded;
/**
 * A boolean value indicating whether the mouth is occluded.
 */
@property AZBoolean *mouthOccluded;
@end
