/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * An array of face groups based on face similarity.
 */
@interface CSFA_GroupResult : NSObject <AZCodable>
/**
 * A partition of the original faces based on face similarity. Groups are
 * ranked by number of faces.
 */
@property NSArray<NSArray<NSUUID*>*> *groups;
/**
 * Face ids array of faces that cannot find any similar faces from original
 * faces.
 */
@property NSArray<NSUUID*> *messyGroup;
/**
* Creates an instance of CSFA_GroupResult class.
* @param groups a partition of the original faces based on face similarity. Groups are ranked by number of faces.
*/
- (id) initWithGroups:(NSArray<NSArray<NSUUID*>*> *)groups;
@end
