/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_TrainingStatusType.h"

/**
 * Defines values for CSFA_TrainingStatusType.
 */
@implementation CSFA_TrainingStatusType
+ (NSArray*)values {
    static NSArray *allValues;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        allValues = @[
            @"nonstarted",
            @"running",
            @"succeeded",
            @"failed"
        ];
    });
    return allValues;
}
/** Enum value nonstarted. */
+ (CSFA_TrainingStatusType*)NONSTARTED {
    return [CSFA_TrainingStatusType values][0];
}
/** Enum value running. */
+ (CSFA_TrainingStatusType*)RUNNING {
    return [CSFA_TrainingStatusType values][1];
}
/** Enum value succeeded. */
+ (CSFA_TrainingStatusType*)SUCCEEDED {
    return [CSFA_TrainingStatusType values][2];
}
/** Enum value failed. */
+ (CSFA_TrainingStatusType*)FAILED {
    return [CSFA_TrainingStatusType values][3];
}
+ (CSFA_TrainingStatusType *)fromString:(NSString *)string {
    if (![[CSFA_TrainingStatusType values]containsObject:string]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"The string is not the enum member" userInfo:nil];
    }
    return (CSFA_TrainingStatusType *)string;
}
+ (NSString *)toStringValue:(CSFA_TrainingStatusType *)value {
    if (![[CSFA_TrainingStatusType values]containsObject:value]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
    }
    return (NSString *)value;
}
@end
