/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_Makeup.h"

@implementation CSFA_Makeup
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.eyeMakeup forKey:@"eyeMakeup"];
    [encoder encodeObject:self.lipMakeup forKey:@"lipMakeup"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _eyeMakeup = [decoder decodeObjectForKey:@"eyeMakeup" objectClass:[AZBoolean class]];
        _lipMakeup = [decoder decodeObjectForKey:@"lipMakeup" objectClass:[AZBoolean class]];
    }
    return self;
}
@end
