/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_VerifyFaceToPersonRequest.h"

@implementation CSFA_VerifyFaceToPersonRequest
- (id) initWithFaceId:(NSUUID *)faceId withPersonId:(NSUUID *)personId {
    self = [super init];
    if (self) {
        _faceId = faceId;
        _personId = personId;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.faceId forKey:@"faceId"];
    [encoder encodeObject:self.personGroupId forKey:@"personGroupId"];
    [encoder encodeObject:self.largePersonGroupId forKey:@"largePersonGroupId"];
    [encoder encodeObject:self.personId forKey:@"personId"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _faceId = [decoder decodeObjectForKey:@"faceId" objectClass:[NSUUID class]];
        _personGroupId = [decoder decodeObjectForKey:@"personGroupId" objectClass:[NSString class]];
        _largePersonGroupId = [decoder decodeObjectForKey:@"largePersonGroupId" objectClass:[NSString class]];
        _personId = [decoder decodeObjectForKey:@"personId" objectClass:[NSUUID class]];
    }
    return self;
}
@end
