/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_NoiseLevel.h"

/**
 * Defines values for CSFA_NoiseLevel.
 */
@implementation CSFA_NoiseLevel
+ (NSArray*)values {
    static NSArray *allValues;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        allValues = @[
            @"Low",
            @"Medium",
            @"High"
        ];
    });
    return allValues;
}
/** Enum value Low. */
+ (CSFA_NoiseLevel*)LOW {
    return [CSFA_NoiseLevel values][0];
}
/** Enum value Medium. */
+ (CSFA_NoiseLevel*)MEDIUM {
    return [CSFA_NoiseLevel values][1];
}
/** Enum value High. */
+ (CSFA_NoiseLevel*)HIGH {
    return [CSFA_NoiseLevel values][2];
}
+ (CSFA_NoiseLevel *)fromString:(NSString *)string {
    if (![[CSFA_NoiseLevel values]containsObject:string]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"The string is not the enum member" userInfo:nil];
    }
    return (CSFA_NoiseLevel *)string;
}
+ (NSString *)toStringValue:(CSFA_NoiseLevel *)value {
    if (![[CSFA_NoiseLevel values]containsObject:value]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
    }
    return (NSString *)value;
}
@end
