/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_FaceList.h"

@implementation CSFA_FaceList
- (id) initWithFaceListId:(NSString *)faceListId {
    self = [super init];
    if (self) {
        _faceListId = faceListId;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject:self.faceListId forKey:@"faceListId"];
    [encoder encodeObject:self.persistedFaces forKey:@"persistedFaces"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super initWithDecoder:decoder]) {
        _faceListId = [decoder decodeObjectForKey:@"faceListId" objectClass:[NSString class]];
        _persistedFaces = [decoder decodeArrayForKey:@"persistedFaces" elementClass:[CSFA_PersistedFace class]];
    }
    return self;
}
@end
