/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for CSFA_BlurLevel.
 */
@interface CSFA_BlurLevel : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(CSFA_BlurLevel *)value;
@property (class, readonly) CSFA_BlurLevel *LOW;
@property (class, readonly) CSFA_BlurLevel *MEDIUM;
@property (class, readonly) CSFA_BlurLevel *HIGH;
@end
