/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_Coordinate.h"

/**
 * A collection of 27-point face landmarks pointing to the important positions
 * of face components.
 */
@interface CSFA_FaceLandmarks : NSObject <AZCodable>
/**
 * The pupilLeft property.
 */
@property CSFA_Coordinate *pupilLeft;
/**
 * The pupilRight property.
 */
@property CSFA_Coordinate *pupilRight;
/**
 * The noseTip property.
 */
@property CSFA_Coordinate *noseTip;
/**
 * The mouthLeft property.
 */
@property CSFA_Coordinate *mouthLeft;
/**
 * The mouthRight property.
 */
@property CSFA_Coordinate *mouthRight;
/**
 * The eyebrowLeftOuter property.
 */
@property CSFA_Coordinate *eyebrowLeftOuter;
/**
 * The eyebrowLeftInner property.
 */
@property CSFA_Coordinate *eyebrowLeftInner;
/**
 * The eyeLeftOuter property.
 */
@property CSFA_Coordinate *eyeLeftOuter;
/**
 * The eyeLeftTop property.
 */
@property CSFA_Coordinate *eyeLeftTop;
/**
 * The eyeLeftBottom property.
 */
@property CSFA_Coordinate *eyeLeftBottom;
/**
 * The eyeLeftInner property.
 */
@property CSFA_Coordinate *eyeLeftInner;
/**
 * The eyebrowRightInner property.
 */
@property CSFA_Coordinate *eyebrowRightInner;
/**
 * The eyebrowRightOuter property.
 */
@property CSFA_Coordinate *eyebrowRightOuter;
/**
 * The eyeRightInner property.
 */
@property CSFA_Coordinate *eyeRightInner;
/**
 * The eyeRightTop property.
 */
@property CSFA_Coordinate *eyeRightTop;
/**
 * The eyeRightBottom property.
 */
@property CSFA_Coordinate *eyeRightBottom;
/**
 * The eyeRightOuter property.
 */
@property CSFA_Coordinate *eyeRightOuter;
/**
 * The noseRootLeft property.
 */
@property CSFA_Coordinate *noseRootLeft;
/**
 * The noseRootRight property.
 */
@property CSFA_Coordinate *noseRootRight;
/**
 * The noseLeftAlarTop property.
 */
@property CSFA_Coordinate *noseLeftAlarTop;
/**
 * The noseRightAlarTop property.
 */
@property CSFA_Coordinate *noseRightAlarTop;
/**
 * The noseLeftAlarOutTip property.
 */
@property CSFA_Coordinate *noseLeftAlarOutTip;
/**
 * The noseRightAlarOutTip property.
 */
@property CSFA_Coordinate *noseRightAlarOutTip;
/**
 * The upperLipTop property.
 */
@property CSFA_Coordinate *upperLipTop;
/**
 * The upperLipBottom property.
 */
@property CSFA_Coordinate *upperLipBottom;
/**
 * The underLipTop property.
 */
@property CSFA_Coordinate *underLipTop;
/**
 * The underLipBottom property.
 */
@property CSFA_Coordinate *underLipBottom;
@end
