/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_BlurLevel.h"

/**
 * Properties describing any presence of blur within the image.
 */
@interface CSFA_Blur : NSObject <AZCodable>
/**
 * An enum value indicating level of blurriness. Possible values include:
 * 'Low', 'Medium', 'High'.
 */
@property CSFA_BlurLevel *blurLevel;
/**
 * A number indicating level of blurriness ranging from 0 to 1.
 */
@property AZDouble *value;
@end
