/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for CSFA_NoiseLevel.
 */
@interface CSFA_NoiseLevel : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(CSFA_NoiseLevel *)value;
@property (class, readonly) CSFA_NoiseLevel *LOW;
@property (class, readonly) CSFA_NoiseLevel *MEDIUM;
@property (class, readonly) CSFA_NoiseLevel *HIGH;
@end
