/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_AccessoryType.h"

/**
 * Defines values for CSFA_AccessoryType.
 */
@implementation CSFA_AccessoryType
+ (NSArray*)values {
    static NSArray *allValues;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        allValues = @[
            @"headWear",
            @"glasses",
            @"mask"
        ];
    });
    return allValues;
}
/** Enum value headWear. */
+ (CSFA_AccessoryType*)HEAD_WEAR {
    return [CSFA_AccessoryType values][0];
}
/** Enum value glasses. */
+ (CSFA_AccessoryType*)GLASSES {
    return [CSFA_AccessoryType values][1];
}
/** Enum value mask. */
+ (CSFA_AccessoryType*)MASK {
    return [CSFA_AccessoryType values][2];
}
+ (CSFA_AccessoryType *)fromString:(NSString *)string {
    if (![[CSFA_AccessoryType values]containsObject:string]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"The string is not the enum member" userInfo:nil];
    }
    return (CSFA_AccessoryType *)string;
}
+ (NSString *)toStringValue:(CSFA_AccessoryType *)value {
    if (![[CSFA_AccessoryType values]containsObject:value]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
    }
    return (NSString *)value;
}
@end
