/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Request body for face to person verification.
 */
@interface CSFA_VerifyFaceToPersonRequest : NSObject <AZCodable>
/**
 * FaceId of the face, comes from Face - Detect.
 */
@property NSUUID *faceId;
/**
 * Using existing personGroupId and personId for fast loading a specified
 * person. personGroupId is created in PersonGroup - Create. Parameter
 * personGroupId and largePersonGroupId should not be provided at the same
 * time.
 */
@property NSString *personGroupId;
/**
 * Using existing largePersonGroupId and personId for fast loading a specified
 * person. largePersonGroupId is created in LargePersonGroup - Create.
 * Parameter personGroupId and largePersonGroupId should not be provided at the
 * same time.
 */
@property NSString *largePersonGroupId;
/**
 * Specify a certain person in a person group or a large person group. personId
 * is created in PersonGroup Person - Create or LargePersonGroup Person -
 * Create.
 */
@property NSUUID *personId;
/**
* Creates an instance of CSFA_VerifyFaceToPersonRequest class.
* @param faceId faceId of the face, comes from Face - Detect.
* @param personId specify a certain person in a person group or a large person group. personId is created in PersonGroup Person - Create or LargePersonGroup Person - Create.
*/
- (id) initWithFaceId:(NSUUID *)faceId withPersonId:(NSUUID *)personId;
@end
