/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Response body for find similar face operation.
 */
@interface CSFA_SimilarFace : NSObject <AZCodable>
/**
 * FaceId of candidate face when find by faceIds. faceId is created by Face -
 * Detect and will expire 24 hours after the detection call.
 */
@property NSUUID *faceId;
/**
 * PersistedFaceId of candidate face when find by faceListId. persistedFaceId
 * in face list is persisted and will not expire. As showed in below response.
 */
@property NSUUID *persistedFaceId;
/**
 * Similarity confidence of the candidate face. The higher confidence, the more
 * similar. Range between [0,1].
 */
@property AZDouble *confidence;
/**
* Creates an instance of CSFA_SimilarFace class.
* @param confidence similarity confidence of the candidate face. The higher confidence, the more similar. Range between [0,1].
*/
- (id) initWithConfidence:(AZDouble *)confidence;
@end
