/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for CSFA_TrainingStatusType.
 */
@interface CSFA_TrainingStatusType : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(CSFA_TrainingStatusType *)value;
@property (class, readonly) CSFA_TrainingStatusType *NONSTARTED;
@property (class, readonly) CSFA_TrainingStatusType *RUNNING;
@property (class, readonly) CSFA_TrainingStatusType *SUCCEEDED;
@property (class, readonly) CSFA_TrainingStatusType *FAILED;
@end
