/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Error body.
 */
@interface CSFA_Error : NSObject <AZCodable>
/**
 * The code property.
 */
@property NSString *code;
/**
 * The message property.
 */
@property NSString *message;
@end
