/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_FaceAttributes.h"

@implementation CSFA_FaceAttributes
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.age forKey:@"age"];
    [encoder encodeObject:self.gender forKey:@"gender"];
    [encoder encodeObject:self.smile forKey:@"smile"];
    [encoder encodeObject:self.facialHair forKey:@"facialHair"];
    [encoder encodeObject:self.glasses forKey:@"glasses"];
    [encoder encodeObject:self.headPose forKey:@"headPose"];
    [encoder encodeObject:self.emotion forKey:@"emotion"];
    [encoder encodeObject:self.hair forKey:@"hair"];
    [encoder encodeObject:self.makeup forKey:@"makeup"];
    [encoder encodeObject:self.occlusion forKey:@"occlusion"];
    [encoder encodeObject:self.accessories forKey:@"accessories"];
    [encoder encodeObject:self.blur forKey:@"blur"];
    [encoder encodeObject:self.exposure forKey:@"exposure"];
    [encoder encodeObject:self.noise forKey:@"noise"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _age = [decoder decodeObjectForKey:@"age" objectClass:[AZDouble class]];
        _gender = [decoder decodeObjectForKey:@"gender" objectClass:[CSFA_Gender class]];
        _smile = [decoder decodeObjectForKey:@"smile" objectClass:[AZDouble class]];
        _facialHair = [decoder decodeObjectForKey:@"facialHair" objectClass:[CSFA_FacialHair class]];
        _glasses = [decoder decodeObjectForKey:@"glasses" objectClass:[CSFA_GlassesType class]];
        _headPose = [decoder decodeObjectForKey:@"headPose" objectClass:[CSFA_HeadPose class]];
        _emotion = [decoder decodeObjectForKey:@"emotion" objectClass:[CSFA_Emotion class]];
        _hair = [decoder decodeObjectForKey:@"hair" objectClass:[CSFA_Hair class]];
        _makeup = [decoder decodeObjectForKey:@"makeup" objectClass:[CSFA_Makeup class]];
        _occlusion = [decoder decodeObjectForKey:@"occlusion" objectClass:[CSFA_Occlusion class]];
        _accessories = [decoder decodeArrayForKey:@"accessories" elementClass:[CSFA_Accessory class]];
        _blur = [decoder decodeObjectForKey:@"blur" objectClass:[CSFA_Blur class]];
        _exposure = [decoder decodeObjectForKey:@"exposure" objectClass:[CSFA_Exposure class]];
        _noise = [decoder decodeObjectForKey:@"noise" objectClass:[CSFA_Noise class]];
    }
    return self;
}
@end
