/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for CSFA_HairColorType.
 */
@interface CSFA_HairColorType : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(CSFA_HairColorType *)value;
@property (class, readonly) CSFA_HairColorType *UNKNOWN;
@property (class, readonly) CSFA_HairColorType *WHITE;
@property (class, readonly) CSFA_HairColorType *GRAY;
@property (class, readonly) CSFA_HairColorType *BLOND;
@property (class, readonly) CSFA_HairColorType *BROWN;
@property (class, readonly) CSFA_HairColorType *RED;
@property (class, readonly) CSFA_HairColorType *BLACK;
@property (class, readonly) CSFA_HairColorType *OTHER;
@end
