/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_ExposureLevel.h"

/**
 * Defines values for CSFA_ExposureLevel.
 */
@implementation CSFA_ExposureLevel
+ (NSArray*)values {
    static NSArray *allValues;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        allValues = @[
            @"UnderExposure",
            @"GoodExposure",
            @"OverExposure"
        ];
    });
    return allValues;
}
/** Enum value UnderExposure. */
+ (CSFA_ExposureLevel*)UNDER_EXPOSURE {
    return [CSFA_ExposureLevel values][0];
}
/** Enum value GoodExposure. */
+ (CSFA_ExposureLevel*)GOOD_EXPOSURE {
    return [CSFA_ExposureLevel values][1];
}
/** Enum value OverExposure. */
+ (CSFA_ExposureLevel*)OVER_EXPOSURE {
    return [CSFA_ExposureLevel values][2];
}
+ (CSFA_ExposureLevel *)fromString:(NSString *)string {
    if (![[CSFA_ExposureLevel values]containsObject:string]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"The string is not the enum member" userInfo:nil];
    }
    return (CSFA_ExposureLevel *)string;
}
+ (NSString *)toStringValue:(CSFA_ExposureLevel *)value {
    if (![[CSFA_ExposureLevel values]containsObject:value]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
    }
    return (NSString *)value;
}
@end
