/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for CSFA_GlassesType.
 */
@interface CSFA_GlassesType : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(CSFA_GlassesType *)value;
@property (class, readonly) CSFA_GlassesType *NO_GLASSES;
@property (class, readonly) CSFA_GlassesType *READING_GLASSES;
@property (class, readonly) CSFA_GlassesType *SUNGLASSES;
@property (class, readonly) CSFA_GlassesType *SWIMMING_GOGGLES;
@end
