/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_NameAndUserDataContract.h"

/**
 * Large person group object.
 */
@interface CSFA_LargePersonGroup : CSFA_NameAndUserDataContract <AZCodable>
/**
 * LargePersonGroupId of the target large person groups.
 */
@property NSString *largePersonGroupId;
/**
* Creates an instance of CSFA_LargePersonGroup class.
* @param largePersonGroupId largePersonGroupId of the target large person groups.
*/
- (id) initWithLargePersonGroupId:(NSString *)largePersonGroupId;
@end
