/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_HeadPose.h"

@implementation CSFA_HeadPose
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.roll forKey:@"roll"];
    [encoder encodeObject:self.yaw forKey:@"yaw"];
    [encoder encodeObject:self.pitch forKey:@"pitch"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _roll = [decoder decodeObjectForKey:@"roll" objectClass:[AZDouble class]];
        _yaw = [decoder decodeObjectForKey:@"yaw" objectClass:[AZDouble class]];
        _pitch = [decoder decodeObjectForKey:@"pitch" objectClass:[AZDouble class]];
    }
    return self;
}
@end
