/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_VerifyFaceToFaceRequest.h"

@implementation CSFA_VerifyFaceToFaceRequest
- (id) initWithFaceId1:(NSUUID *)faceId1 withFaceId2:(NSUUID *)faceId2 {
    self = [super init];
    if (self) {
        _faceId1 = faceId1;
        _faceId2 = faceId2;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.faceId1 forKey:@"faceId1"];
    [encoder encodeObject:self.faceId2 forKey:@"faceId2"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _faceId1 = [decoder decodeObjectForKey:@"faceId1" objectClass:[NSUUID class]];
        _faceId2 = [decoder decodeObjectForKey:@"faceId2" objectClass:[NSUUID class]];
    }
    return self;
}
@end
