/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_DetectedFace.h"

@implementation CSFA_DetectedFace
- (id) initWithFaceRectangle:(CSFA_FaceRectangle *)faceRectangle {
    self = [super init];
    if (self) {
        _faceRectangle = faceRectangle;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.faceId forKey:@"faceId"];
    [encoder encodeObject:self.faceRectangle forKey:@"faceRectangle"];
    [encoder encodeObject:self.faceLandmarks forKey:@"faceLandmarks"];
    [encoder encodeObject:self.faceAttributes forKey:@"faceAttributes"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _faceId = [decoder decodeObjectForKey:@"faceId" objectClass:[NSUUID class]];
        _faceRectangle = [decoder decodeObjectForKey:@"faceRectangle" objectClass:[CSFA_FaceRectangle class]];
        _faceLandmarks = [decoder decodeObjectForKey:@"faceLandmarks" objectClass:[CSFA_FaceLandmarks class]];
        _faceAttributes = [decoder decodeObjectForKey:@"faceAttributes" objectClass:[CSFA_FaceAttributes class]];
    }
    return self;
}
@end
