/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_FaceRectangle.h"
#import "CSFA_FaceLandmarks.h"
#import "CSFA_FaceAttributes.h"

/**
 * Detected Face object.
 */
@interface CSFA_DetectedFace : NSObject <AZCodable>
/**
 * The faceId property.
 */
@property NSUUID *faceId;
/**
 * The faceRectangle property.
 */
@property CSFA_FaceRectangle *faceRectangle;
/**
 * The faceLandmarks property.
 */
@property CSFA_FaceLandmarks *faceLandmarks;
/**
 * The faceAttributes property.
 */
@property CSFA_FaceAttributes *faceAttributes;
/**
* Creates an instance of CSFA_DetectedFace class.
* @param faceRectangle the faceRectangle value.
*/
- (id) initWithFaceRectangle:(CSFA_FaceRectangle *)faceRectangle;
@end
