/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_IdentifyCandidate.h"

@implementation CSFA_IdentifyCandidate
- (id) initWithPersonId:(NSUUID *)personId withConfidence:(AZDouble *)confidence {
    self = [super init];
    if (self) {
        _personId = personId;
        _confidence = confidence;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.personId forKey:@"personId"];
    [encoder encodeObject:self.confidence forKey:@"confidence"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _personId = [decoder decodeObjectForKey:@"personId" objectClass:[NSUUID class]];
        _confidence = [decoder decodeObjectForKey:@"confidence" objectClass:[AZDouble class]];
    }
    return self;
}
@end
