/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_FindSimilarMatchMode.h"

/**
 * Request body for find similar operation.
 */
@interface CSFA_FindSimilarRequest : NSObject <AZCodable>
/**
 * FaceId of the query face. User needs to call Face - Detect first to get a
 * valid faceId. Note that this faceId is not persisted and will expire 24
 * hours after the detection call.
 */
@property NSUUID *faceId;
/**
 * An existing user-specified unique candidate face list, created in Face List
 * - Create a Face List. Face list contains a set of persistedFaceIds which are
 * persisted and will never expire. Parameter faceListId, largeFaceListId and
 * faceIds should not be provided at the same time。.
 */
@property NSString *faceListId;
/**
 * An existing user-specified unique candidate large face list, created in
 * LargeFaceList - Create. Large face list contains a set of persistedFaceIds
 * which are persisted and will never expire. Parameter faceListId,
 * largeFaceListId and faceIds should not be provided at the same time.
 */
@property NSString *largeFaceListId;
/**
 * An array of candidate faceIds. All of them are created by Face - Detect and
 * the faceIds will expire 24 hours after the detection call. The number of
 * faceIds is limited to 1000. Parameter faceListId, largeFaceListId and
 * faceIds should not be provided at the same time.
 */
@property NSArray<NSUUID*> *faceIds;
/**
 * The number of top similar faces returned. The valid range is [1, 1000].
 */
@property AZInteger *maxNumOfCandidatesReturned;
/**
 * Similar face searching mode. It can be "matchPerson" or "matchFace".
 * Possible values include: 'matchPerson', 'matchFace'.
 */
@property CSFA_FindSimilarMatchMode *mode;
/**
* Creates an instance of CSFA_FindSimilarRequest class.
* @param faceId faceId of the query face. User needs to call Face - Detect first to get a valid faceId. Note that this faceId is not persisted and will expire 24 hours after the detection call.
*/
- (id) initWithFaceId:(NSUUID *)faceId;
@end
