/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_FacialHair.h"

@implementation CSFA_FacialHair
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.moustache forKey:@"moustache"];
    [encoder encodeObject:self.beard forKey:@"beard"];
    [encoder encodeObject:self.sideburns forKey:@"sideburns"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _moustache = [decoder decodeObjectForKey:@"moustache" objectClass:[AZDouble class]];
        _beard = [decoder decodeObjectForKey:@"beard" objectClass:[AZDouble class]];
        _sideburns = [decoder decodeObjectForKey:@"sideburns" objectClass:[AZDouble class]];
    }
    return self;
}
@end
