/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_Person.h"

@implementation CSFA_Person
- (id) initWithPersonId:(NSUUID *)personId {
    self = [super init];
    if (self) {
        _personId = personId;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject:self.personId forKey:@"personId"];
    [encoder encodeObject:self.persistedFaceIds forKey:@"persistedFaceIds"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super initWithDecoder:decoder]) {
        _personId = [decoder decodeObjectForKey:@"personId" objectClass:[NSUUID class]];
        _persistedFaceIds = [decoder decodeArrayForKey:@"persistedFaceIds" elementClass:[NSUUID class]];
    }
    return self;
}
@end
