/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Request body for group request.
 */
@interface CSFA_GroupRequest : NSObject <AZCodable>
/**
 * Array of candidate faceId created by Face - Detect. The maximum is 1000
 * faces.
 */
@property NSArray<NSUUID*> *faceIds;
/**
* Creates an instance of CSFA_GroupRequest class.
* @param faceIds array of candidate faceId created by Face - Detect. The maximum is 1000 faces.
*/
- (id) initWithFaceIds:(NSArray<NSUUID*> *)faceIds;
@end
