/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Coordinates within an image.
 */
@interface CSFA_Coordinate : NSObject <AZCodable>
/**
 * The horizontal component, in pixels.
 */
@property AZDouble *x;
/**
 * The vertical component, in pixels.
 */
@property AZDouble *y;
/**
* Creates an instance of CSFA_Coordinate class.
* @param x the horizontal component, in pixels.
* @param y the vertical component, in pixels.
*/
- (id) initWithX:(AZDouble *)x withY:(AZDouble *)y;
@end
