/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_Hair.h"

@implementation CSFA_Hair
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.bald forKey:@"bald"];
    [encoder encodeObject:self.invisible forKey:@"invisible"];
    [encoder encodeObject:self.hairColor forKey:@"hairColor"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _bald = [decoder decodeObjectForKey:@"bald" objectClass:[AZDouble class]];
        _invisible = [decoder decodeObjectForKey:@"invisible" objectClass:[AZBoolean class]];
        _hairColor = [decoder decodeArrayForKey:@"hairColor" elementClass:[CSFA_HairColor class]];
    }
    return self;
}
@end
