/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_IdentifyRequest.h"

@implementation CSFA_IdentifyRequest
- (id) initWithFaceIds:(NSArray<NSUUID*> *)faceIds {
    self = [super init];
    if (self) {
        _faceIds = faceIds;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.faceIds forKey:@"faceIds"];
    [encoder encodeObject:self.personGroupId forKey:@"personGroupId"];
    [encoder encodeObject:self.largePersonGroupId forKey:@"largePersonGroupId"];
    [encoder encodeObject:self.maxNumOfCandidatesReturned forKey:@"maxNumOfCandidatesReturned"];
    [encoder encodeObject:self.confidenceThreshold forKey:@"confidenceThreshold"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _faceIds = [decoder decodeArrayForKey:@"faceIds" elementClass:[NSUUID class]];
        _personGroupId = [decoder decodeObjectForKey:@"personGroupId" objectClass:[NSString class]];
        _largePersonGroupId = [decoder decodeObjectForKey:@"largePersonGroupId" objectClass:[NSString class]];
        _maxNumOfCandidatesReturned = [decoder decodeObjectForKey:@"maxNumOfCandidatesReturned" objectClass:[AZInteger class]];
        _confidenceThreshold = [decoder decodeObjectForKey:@"confidenceThreshold" objectClass:[AZDouble class]];
    }
    return self;
}
@end
