/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_NameAndUserDataContract.h"

/**
 * Person object.
 */
@interface CSFA_Person : CSFA_NameAndUserDataContract <AZCodable>
/**
 * PersonId of the target face list.
 */
@property NSUUID *personId;
/**
 * PersistedFaceIds of registered faces in the person. These persistedFaceIds
 * are returned from Person - Add a Person Face, and will not expire.
 */
@property NSArray<NSUUID*> *persistedFaceIds;
/**
* Creates an instance of CSFA_Person class.
* @param personId personId of the target face list.
*/
- (id) initWithPersonId:(NSUUID *)personId;
@end
