/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Request body for identify face operation.
 */
@interface CSFA_IdentifyRequest : NSObject <AZCodable>
/**
 * Array of query faces faceIds, created by the Face - Detect. Each of the
 * faces are identified independently. The valid number of faceIds is between
 * [1, 10].
 */
@property NSArray<NSUUID*> *faceIds;
/**
 * PersonGroupId of the target person group, created by PersonGroup - Create.
 * Parameter personGroupId and largePersonGroupId should not be provided at the
 * same time.
 */
@property NSString *personGroupId;
/**
 * LargePersonGroupId of the target large person group, created by
 * LargePersonGroup - Create. Parameter personGroupId and largePersonGroupId
 * should not be provided at the same time.
 */
@property NSString *largePersonGroupId;
/**
 * The range of maxNumOfCandidatesReturned is between 1 and 5 (default is 1).
 */
@property AZInteger *maxNumOfCandidatesReturned;
/**
 * Confidence threshold of identification, used to judge whether one face
 * belong to one person. The range of confidenceThreshold is [0, 1] (default
 * specified by algorithm).
 */
@property AZDouble *confidenceThreshold;
/**
* Creates an instance of CSFA_IdentifyRequest class.
* @param faceIds array of query faces faceIds, created by the Face - Detect. Each of the faces are identified independently. The valid number of faceIds is between [1, 10].
*/
- (id) initWithFaceIds:(NSArray<NSUUID*> *)faceIds;
@end
