/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_IdentifyResult.h"

@implementation CSFA_IdentifyResult
- (id) initWithFaceId:(NSUUID *)faceId withCandidates:(NSArray<CSFA_IdentifyCandidate*> *)candidates {
    self = [super init];
    if (self) {
        _faceId = faceId;
        _candidates = candidates;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.faceId forKey:@"faceId"];
    [encoder encodeObject:self.candidates forKey:@"candidates"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _faceId = [decoder decodeObjectForKey:@"faceId" objectClass:[NSUUID class]];
        _candidates = [decoder decodeArrayForKey:@"candidates" elementClass:[CSFA_IdentifyCandidate class]];
    }
    return self;
}
@end
