/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_TrainingStatus.h"

@implementation CSFA_TrainingStatus
- (id) initWithStatus:(CSFA_TrainingStatusType *)status withCreated:(AZDateTime *)created {
    self = [super init];
    if (self) {
        _status = status;
        _created = created;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.status forKey:@"status"];
    [encoder encodeObject:self.created forKey:@"createdDateTime"];
    [encoder encodeObject:self.lastAction forKey:@"lastActionDateTime"];
    [encoder encodeObject:self.lastSuccessfulTraining forKey:@"lastSuccessfulTrainingDateTime"];
    [encoder encodeObject:self.message forKey:@"message"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _status = [decoder decodeObjectForKey:@"status" objectClass:[CSFA_TrainingStatusType class]];
        _created = [decoder decodeObjectForKey:@"createdDateTime" objectClass:[AZDateTime class]];
        _lastAction = [decoder decodeObjectForKey:@"lastActionDateTime" objectClass:[AZDateTime class]];
        _lastSuccessfulTraining = [decoder decodeObjectForKey:@"lastSuccessfulTrainingDateTime" objectClass:[AZDateTime class]];
        _message = [decoder decodeObjectForKey:@"message" objectClass:[NSString class]];
    }
    return self;
}
@end
