/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_Coordinate.h"

@implementation CSFA_Coordinate
- (id) initWithX:(AZDouble *)x withY:(AZDouble *)y {
    self = [super init];
    if (self) {
        _x = x;
        _y = y;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.x forKey:@"x"];
    [encoder encodeObject:self.y forKey:@"y"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _x = [decoder decodeObjectForKey:@"x" objectClass:[AZDouble class]];
        _y = [decoder decodeObjectForKey:@"y" objectClass:[AZDouble class]];
    }
    return self;
}
@end
