/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Request body for face to face verification.
 */
@interface CSFA_VerifyFaceToFaceRequest : NSObject <AZCodable>
/**
 * FaceId of the first face, comes from Face - Detect.
 */
@property NSUUID *faceId1;
/**
 * FaceId of the second face, comes from Face - Detect.
 */
@property NSUUID *faceId2;
/**
* Creates an instance of CSFA_VerifyFaceToFaceRequest class.
* @param faceId1 faceId of the first face, comes from Face - Detect.
* @param faceId2 faceId of the second face, comes from Face - Detect.
*/
- (id) initWithFaceId1:(NSUUID *)faceId1 withFaceId2:(NSUUID *)faceId2;
@end
