/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_Blur.h"

@implementation CSFA_Blur
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.blurLevel forKey:@"blurLevel"];
    [encoder encodeObject:self.value forKey:@"value"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _blurLevel = [decoder decodeObjectForKey:@"blurLevel" objectClass:[CSFA_BlurLevel class]];
        _value = [decoder decodeObjectForKey:@"value" objectClass:[AZDouble class]];
    }
    return self;
}
@end
