/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_PersistedFace.h"

@implementation CSFA_PersistedFace
- (id) initWithPersistedFaceId:(NSUUID *)persistedFaceId {
    self = [super init];
    if (self) {
        _persistedFaceId = persistedFaceId;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.persistedFaceId forKey:@"persistedFaceId"];
    [encoder encodeObject:self.userData forKey:@"userData"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _persistedFaceId = [decoder decodeObjectForKey:@"persistedFaceId" objectClass:[NSUUID class]];
        _userData = [decoder decodeObjectForKey:@"userData" objectClass:[NSString class]];
    }
    return self;
}
@end
