/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_HairColorType.h"

/**
 * Defines values for CSFA_HairColorType.
 */
@implementation CSFA_HairColorType
+ (NSArray*)values {
    static NSArray *allValues;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        allValues = @[
            @"unknown",
            @"white",
            @"gray",
            @"blond",
            @"brown",
            @"red",
            @"black",
            @"other"
        ];
    });
    return allValues;
}
/** Enum value unknown. */
+ (CSFA_HairColorType*)UNKNOWN {
    return [CSFA_HairColorType values][0];
}
/** Enum value white. */
+ (CSFA_HairColorType*)WHITE {
    return [CSFA_HairColorType values][1];
}
/** Enum value gray. */
+ (CSFA_HairColorType*)GRAY {
    return [CSFA_HairColorType values][2];
}
/** Enum value blond. */
+ (CSFA_HairColorType*)BLOND {
    return [CSFA_HairColorType values][3];
}
/** Enum value brown. */
+ (CSFA_HairColorType*)BROWN {
    return [CSFA_HairColorType values][4];
}
/** Enum value red. */
+ (CSFA_HairColorType*)RED {
    return [CSFA_HairColorType values][5];
}
/** Enum value black. */
+ (CSFA_HairColorType*)BLACK {
    return [CSFA_HairColorType values][6];
}
/** Enum value other. */
+ (CSFA_HairColorType*)OTHER {
    return [CSFA_HairColorType values][7];
}
+ (CSFA_HairColorType *)fromString:(NSString *)string {
    if (![[CSFA_HairColorType values]containsObject:string]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"The string is not the enum member" userInfo:nil];
    }
    return (CSFA_HairColorType *)string;
}
+ (NSString *)toStringValue:(CSFA_HairColorType *)value {
    if (![[CSFA_HairColorType values]containsObject:value]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
    }
    return (NSString *)value;
}
@end
