/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Properties indicating head pose of the face.
 */
@interface CSFA_HeadPose : NSObject <AZCodable>
/**
 * The roll property.
 */
@property AZDouble *roll;
/**
 * The yaw property.
 */
@property AZDouble *yaw;
/**
 * The pitch property.
 */
@property AZDouble *pitch;
@end
