/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Properties describing facial emotion in form of confidence ranging from 0 to
 * 1.
 */
@interface CSFA_Emotion : NSObject <AZCodable>
/**
 * The anger property.
 */
@property AZDouble *anger;
/**
 * The contempt property.
 */
@property AZDouble *contempt;
/**
 * The disgust property.
 */
@property AZDouble *disgust;
/**
 * The fear property.
 */
@property AZDouble *fear;
/**
 * The happiness property.
 */
@property AZDouble *happiness;
/**
 * The neutral property.
 */
@property AZDouble *neutral;
/**
 * The sadness property.
 */
@property AZDouble *sadness;
/**
 * The surprise property.
 */
@property AZDouble *surprise;
@end
