/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Result of the verify operation.
 */
@interface CSFA_VerifyResult : NSObject <AZCodable>
/**
 * True if the two faces belong to the same person or the face belongs to the
 * person, otherwise false.
 */
@property AZBoolean *isIdentical;
/**
 * A number indicates the similarity confidence of whether two faces belong to
 * the same person, or whether the face belongs to the person. By default,
 * isIdentical is set to True if similarity confidence is greater than or equal
 * to 0.5. This is useful for advanced users to override "isIdentical" and
 * fine-tune the result on their own data.
 */
@property AZDouble *confidence;
/**
* Creates an instance of CSFA_VerifyResult class.
* @param isIdentical true if the two faces belong to the same person or the face belongs to the person, otherwise false.
* @param confidence a number indicates the similarity confidence of whether two faces belong to the same person, or whether the face belongs to the person. By default, isIdentical is set to True if similarity confidence is greater than or equal to 0.5. This is useful for advanced users to override "isIdentical" and fine-tune the result on their own data.
*/
- (id) initWithIsIdentical:(AZBoolean *)isIdentical withConfidence:(AZDouble *)confidence;
@end
