/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_AccessoryType.h"

/**
 * Accessory item and corresponding confidence level.
 */
@interface CSFA_Accessory : NSObject <AZCodable>
/**
 * Type of an accessory. Possible values include: 'headWear', 'glasses',
 * 'mask'.
 */
@property CSFA_AccessoryType *type;
/**
 * Confidence level of an accessory.
 */
@property AZDouble *confidence;
@end
