/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_GroupRequest.h"

@implementation CSFA_GroupRequest
- (id) initWithFaceIds:(NSArray<NSUUID*> *)faceIds {
    self = [super init];
    if (self) {
        _faceIds = faceIds;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.faceIds forKey:@"faceIds"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _faceIds = [decoder decodeArrayForKey:@"faceIds" elementClass:[NSUUID class]];
    }
    return self;
}
@end
