/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_TrainingStatusType.h"

/**
 * Training status object.
 */
@interface CSFA_TrainingStatus : NSObject <AZCodable>
/**
 * Training status: notstarted, running, succeeded, failed. If the training
 * process is waiting to perform, the status is notstarted. If the training is
 * ongoing, the status is running. Status succeed means this person group or
 * large person group is ready for Face - Identify, or this large face list is
 * ready for Face - Find Similar. Status failed is often caused by no person or
 * no persisted face exist in the person group or large person group, or no
 * persisted face exist in the large face list. Possible values include:
 * 'nonstarted', 'running', 'succeeded', 'failed'.
 */
@property CSFA_TrainingStatusType *status;
/**
 * A combined UTC date and time string that describes the created time of the
 * person group, large person group or large face list.
 */
@property AZDateTime *created;
/**
 * A combined UTC date and time string that describes the last modify time of
 * the person group, large person group or large face list, could be null value
 * when the group is not successfully trained.
 */
@property AZDateTime *lastAction;
/**
 * A combined UTC date and time string that describes the last successful
 * training time of the person group, large person group or large face list.
 */
@property AZDateTime *lastSuccessfulTraining;
/**
 * Show failure message when training failed (omitted when training succeed).
 */
@property NSString *message;
/**
* Creates an instance of CSFA_TrainingStatus class.
* @param status training status: notstarted, running, succeeded, failed. If the training process is waiting to perform, the status is notstarted. If the training is ongoing, the status is running. Status succeed means this person group or large person group is ready for Face - Identify, or this large face list is ready for Face - Find Similar. Status failed is often caused by no person or no persisted face exist in the person group or large person group, or no persisted face exist in the large face list. Possible values include: 'nonstarted', 'running', 'succeeded', 'failed'.
* @param created a combined UTC date and time string that describes the created time of the person group, large person group or large face list.
*/
- (id) initWithStatus:(CSFA_TrainingStatusType *)status withCreated:(AZDateTime *)created;
@end
