/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_IdentifyCandidate.h"

/**
 * Response body for identify face operation.
 */
@interface CSFA_IdentifyResult : NSObject <AZCodable>
/**
 * FaceId of the query face.
 */
@property NSUUID *faceId;
/**
 * Identified person candidates for that face (ranked by confidence). Array
 * size should be no larger than input maxNumOfCandidatesReturned. If no person
 * is identified, will return an empty array.
 */
@property NSArray<CSFA_IdentifyCandidate*> *candidates;
/**
* Creates an instance of CSFA_IdentifyResult class.
* @param faceId faceId of the query face.
* @param candidates identified person candidates for that face (ranked by confidence). Array size should be no larger than input maxNumOfCandidatesReturned. If no person is identified, will return an empty array.
*/
- (id) initWithFaceId:(NSUUID *)faceId withCandidates:(NSArray<CSFA_IdentifyCandidate*> *)candidates;
@end
