/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_BlurLevel.h"

/**
 * Defines values for CSFA_BlurLevel.
 */
@implementation CSFA_BlurLevel
+ (NSArray*)values {
    static NSArray *allValues;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        allValues = @[
            @"Low",
            @"Medium",
            @"High"
        ];
    });
    return allValues;
}
/** Enum value Low. */
+ (CSFA_BlurLevel*)LOW {
    return [CSFA_BlurLevel values][0];
}
/** Enum value Medium. */
+ (CSFA_BlurLevel*)MEDIUM {
    return [CSFA_BlurLevel values][1];
}
/** Enum value High. */
+ (CSFA_BlurLevel*)HIGH {
    return [CSFA_BlurLevel values][2];
}
+ (CSFA_BlurLevel *)fromString:(NSString *)string {
    if (![[CSFA_BlurLevel values]containsObject:string]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"The string is not the enum member" userInfo:nil];
    }
    return (CSFA_BlurLevel *)string;
}
+ (NSString *)toStringValue:(CSFA_BlurLevel *)value {
    if (![[CSFA_BlurLevel values]containsObject:value]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
    }
    return (NSString *)value;
}
@end
