/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_LargeFaceList.h"

@implementation CSFA_LargeFaceList
- (id) initWithLargeFaceListId:(NSString *)largeFaceListId {
    self = [super init];
    if (self) {
        _largeFaceListId = largeFaceListId;
    }
    return self;
}
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject:self.largeFaceListId forKey:@"largeFaceListId"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super initWithDecoder:decoder]) {
        _largeFaceListId = [decoder decodeObjectForKey:@"largeFaceListId" objectClass:[NSString class]];
    }
    return self;
}
@end
