/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * All possible faces that may qualify.
 */
@interface CSFA_IdentifyCandidate : NSObject <AZCodable>
/**
 * Id of candidate.
 */
@property NSUUID *personId;
/**
 * Confidence threshold of identification, used to judge whether one face
 * belong to one person. The range of confidenceThreshold is [0, 1] (default
 * specified by algorithm).
 */
@property AZDouble *confidence;
/**
* Creates an instance of CSFA_IdentifyCandidate class.
* @param personId id of candidate.
* @param confidence confidence threshold of identification, used to judge whether one face belong to one person. The range of confidenceThreshold is [0, 1] (default specified by algorithm).
*/
- (id) initWithPersonId:(NSUUID *)personId withConfidence:(AZDouble *)confidence;
@end
