/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSFA_PersonGroup.h"
#import "CSFA_TrainingStatus.h"
@class AZOperationError;

/**
 * An protocol provides access to all CSFA_PersonGroups operations
 */
@protocol CSFA_PersonGroupsProtocol

/**
 * Create a new person group with specified personGroupId, name and user-provided userData.
 *
 * @param personGroupId Id referencing a particular person group.
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)createWithPersonGroupId:(NSString *)personGroupId withCallback:(void(^)(AZOperationError *))callback;

/**
 * Create a new person group with specified personGroupId, name and user-provided userData.
 *
 * @param personGroupId Id referencing a particular person group.
 * @param name User defined name, maximum length is 128.
 * @param userData User specified data. Length should not exceed 16KB.
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)createWithPersonGroupId:(NSString *)personGroupId withName:(NSString *)name withUserData:(NSString *)userData withCallback:(void(^)(AZOperationError *))callback;

/**
 * Delete an existing person group. Persisted face features of all people in the person group will also be deleted.
 *
 * @param personGroupId Id referencing a particular person group.
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)deleteWithPersonGroupId:(NSString *)personGroupId withCallback:(void(^)(AZOperationError *))callback;

/**
 * Retrieve the information of a person group, including its name and userData.
 *
 * @param personGroupId Id referencing a particular person group.
 * @param callback A block where CSFA_PersonGroup is a result object and AZOperationError is nil, if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)getWithPersonGroupId:(NSString *)personGroupId withCallback:(void(^)(CSFA_PersonGroup *, AZOperationError *))callback;

/**
 * Update an existing person group's display name and userData. The properties which does not appear in request body will not be updated.
 *
 * @param personGroupId Id referencing a particular person group.
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)updateWithPersonGroupId:(NSString *)personGroupId withCallback:(void(^)(AZOperationError *))callback;

/**
 * Update an existing person group's display name and userData. The properties which does not appear in request body will not be updated.
 *
 * @param personGroupId Id referencing a particular person group.
 * @param name User defined name, maximum length is 128.
 * @param userData User specified data. Length should not exceed 16KB.
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)updateWithPersonGroupId:(NSString *)personGroupId withName:(NSString *)name withUserData:(NSString *)userData withCallback:(void(^)(AZOperationError *))callback;

/**
 * Retrieve the training status of a person group (completed or ongoing).
 *
 * @param personGroupId Id referencing a particular person group.
 * @param callback A block where CSFA_TrainingStatus is a result object and AZOperationError is nil, if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)getTrainingStatusWithPersonGroupId:(NSString *)personGroupId withCallback:(void(^)(CSFA_TrainingStatus *, AZOperationError *))callback;

/**
 * List person groups and their information.
 *
 * @param callback A block where NSArray<CSFA_PersonGroup*> is a result object and AZOperationError is nil, if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)listWithCallback:(void(^)(NSArray<CSFA_PersonGroup*> *, AZOperationError *))callback;

/**
 * List person groups and their information.
 *
 * @param start List person groups from the least personGroupId greater than the "start".
 * @param top The number of person groups to list.
 * @param callback A block where NSArray<CSFA_PersonGroup*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)listWithStart:(NSString *)start withTop:(AZInteger *)top withCallback:(void(^)(NSArray<CSFA_PersonGroup*> *, AZOperationError *))callback;

/**
 * Queue a person group training task, the training task may not be started immediately.
 *
 * @param personGroupId Id referencing a particular person group.
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)trainWithPersonGroupId:(NSString *)personGroupId withCallback:(void(^)(AZOperationError *))callback;

@end

/**
* The protocol implementation
*/
@class CSFA_FaceClientService;

@interface CSFA_PersonGroups : NSObject <CSFA_PersonGroupsProtocol>
@property (readonly) CSFA_FaceClientService *service;
- (instancetype)initWithService:(CSFA_FaceClientService *)service;
@end
