/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSFA_FaceClientService.h"

/**
 * Initializes a new instance of the CSFA_FaceClientService class.
 */
@implementation CSFA_FaceClientService
- (instancetype)initWithEndpoint:(NSString*)endpoint  withSubscriptionKey:(NSString*)key{
    self = [super init];
    if (self) {
        _DEFAULT_BASE_URL = @"https://{Endpoint}/face/v1.0";
        _key = key;
        _specialHeaders = @{@"ocp-apim-subscription-key" : self.key};
        _endpoint = endpoint;
    }
    return self;
}

+ (id<CSFA_FaceClientServiceProtocol>)createWithEndpoint:(NSString*)endpoint  withSubscriptionKey:(NSString*)key{
    CSFA_FaceClientService* client = [[CSFA_FaceClientService alloc] initWithEndpoint:endpoint withSubscriptionKey:key];
    return client;
}

/**
 * The CSFA_Faces object to access its operations.
 */
- (id<CSFA_FacesProtocol>) faces {
     id<CSFA_FacesProtocol> op = [[CSFA_Faces alloc] initWithService:self];
     return op;
}

/**
 * The CSFA_PersonGroupPersons object to access its operations.
 */
- (id<CSFA_PersonGroupPersonsProtocol>) personGroupPersons {
     id<CSFA_PersonGroupPersonsProtocol> op = [[CSFA_PersonGroupPersons alloc] initWithService:self];
     return op;
}

/**
 * The CSFA_PersonGroups object to access its operations.
 */
- (id<CSFA_PersonGroupsProtocol>) personGroups {
     id<CSFA_PersonGroupsProtocol> op = [[CSFA_PersonGroups alloc] initWithService:self];
     return op;
}

/**
 * The CSFA_FaceLists object to access its operations.
 */
- (id<CSFA_FaceListsProtocol>) faceLists {
     id<CSFA_FaceListsProtocol> op = [[CSFA_FaceLists alloc] initWithService:self];
     return op;
}

/**
 * The CSFA_LargePersonGroupPersons object to access its operations.
 */
- (id<CSFA_LargePersonGroupPersonsProtocol>) largePersonGroupPersons {
     id<CSFA_LargePersonGroupPersonsProtocol> op = [[CSFA_LargePersonGroupPersons alloc] initWithService:self];
     return op;
}

/**
 * The CSFA_LargePersonGroups object to access its operations.
 */
- (id<CSFA_LargePersonGroupsProtocol>) largePersonGroups {
     id<CSFA_LargePersonGroupsProtocol> op = [[CSFA_LargePersonGroups alloc] initWithService:self];
     return op;
}

/**
 * The CSFA_LargeFaceLists object to access its operations.
 */
- (id<CSFA_LargeFaceListsProtocol>) largeFaceLists {
     id<CSFA_LargeFaceListsProtocol> op = [[CSFA_LargeFaceLists alloc] initWithService:self];
     return op;
}
@end
